#!/usr/bin/env python3
"""pack4.py DUMP CELL IMAGE OUT ALPHABET_H - rewrite a RelF image's runs
of primitives into tagged-NIBBLE packs, for engine/pack4.c.

The sibling of pack8.py. Same in-place rewrite, same dead cells left
where they were so that no address moves and no relocation pass is
needed, same reasons - see that file's header, which is the longer
explanation of both.

The one real difference is the ALPHABET. An opcode is four bits, so only
sixteen primitives can be packed at all and everything else both stays a
plain cell and ENDS the run it interrupts. Which sixteen is therefore a
design decision with teeth, and it is made here by counting.

HOW THE ALPHABET IS CHOSEN. Static frequency in the image being packed:
the sixteen packable primitives that appear most often in compiled word
bodies. Static, not dynamic, because the question a nibble alphabet
answers is "which operations do I want to make SMALL", and size depends
on how often an operation appears rather than how often it runs.

ENCODING-COMPARISON.md notes that the two orders disagree - it gives
DROP at rank 6 static and rank 20 dynamic, LSHIFT at 28 static and 13
dynamic - so an alphabet chosen for size is not the one that would be
chosen for speed, and with only sixteen slots there is no room to serve
both. That is a real cost of the narrow field and it is worth saying
plainly rather than splitting the difference.

If ALPHABET_H already exists it is READ rather than recomputed, so that
the 32-bit and 64-bit builds share one alphabet and one engine binary
per width can run either image.
"""
import os
import re
import sys
from collections import Counter

DUMP, CELL, IMG, OUT, ALPHA_H = (sys.argv[1], int(sys.argv[2]),
                                 sys.argv[3], sys.argv[4], sys.argv[5])

_argv = list(sys.argv)
sys.argv = ['sod16.py', DUMP, str(CELL)]
_src = open(__file__.replace('pack4.py', 'sod16.py')).read()
_lib = _src[:_src.index('# ---- decode tokens back')]
G = {'__name__': 'sod16lib'}
exec(compile(_lib, 'sod16lib', 'exec'), G)
sys.argv = _argv

words, read_ops, op_cells = G['words'], G['read_ops'], G['op_cells']
idx_of, cells, prims = G['idx_of'], G['cells'], G['prims']
PRIMS = set(prims)

START = None
for line in open(DUMP, errors='replace'):
    m = re.match(r'^S (\d+) (\d+)', line)
    if m:
        START, HERE = int(m.group(1)), int(m.group(2))
        break
if START is None:
    sys.exit("no S anchor line in %s" % DUMP)

blob = bytearray(open(IMG, 'rb').read())
HDR = 8
IMG_END = START + len(blob) - HDR

NIBBLES = (CELL - 1) * 2          # opcode fields beside the tag byte
MAXOPS = min(NIBBLES, 14)         # the count field holds 1..16


def bodies():
    """Every code word that is really in the image, with its ops."""
    for w in words:
        if w['e'] > IMG_END or w['n'] in PRIMS:
            continue
        ops = read_ops(w)
        if ops is not None:
            yield w, ops


# ---- the alphabet ---------------------------------------------------
if os.path.exists(ALPHA_H):
    # Match only the entry lines. Matching every line containing a
    # comment picked up the generated file's own header, which shifted
    # the whole alphabet by one and produced a nibble value of 16.
    alpha = re.findall(r'^\s*\d+,\s*/\*\s*(\S+)\s*\*/',
                       open(ALPHA_H).read(), re.M)
else:
    freq = Counter()
    for w, ops in bodies():
        for k, pl in ops:
            if k == 'P':
                freq[pl] += 1
    alpha = [n for n, _ in freq.most_common(16)]
    while len(alpha) < 16:
        alpha.append('NOOP')
    with open(ALPHA_H, 'w') as f:
        f.write("/* generated by tools/pack4.py from %s - do not edit */\n"
                % os.path.basename(DUMP))
        for n in alpha:
            f.write("    %3d, /* %s */\n" % (idx_of[n], n))
ALPHA = {n: i for i, n in enumerate(alpha)}

# ---- pack -----------------------------------------------------------
tails = set()
starts = {w['s'] for w in words}
for w in words:
    v = cells.get(w['s'])
    if v is not None and not (v & 1):
        t = w['s'] + CELL + v
        if t not in starts:
            tails.add(t)


def put_cell(addr, value):
    off = HDR + (addr - START)
    blob[off:off + CELL] = value.to_bytes(CELL, 'little')


packs = runs = saved = total = packable = 0

for w, ops in bodies():
    at, off = [], 0
    for k, pl in ops:
        at.append(off)
        off += op_cells(k, pl)

    breaks = set()
    for j, (k, pl) in enumerate(ops):
        if k in ('BR', 'QBR'):
            breaks.add(at[j] + CELL + pl)
        elif k == 'OPD':
            breaks.add(at[j] + pl)
    for t in tails:
        if w['s'] < t < w['e']:
            breaks.add(t - w['s'])

    run = []

    def flush():
        global packs, runs, saved
        if len(run) >= 2:
            runs += 1
            i = 0
            while i < len(run):
                chunk = run[i:i + MAXOPS]
                if len(chunk) < 2:
                    break
                value = 3 | ((len(chunk) - 1) << 2)
                for n, o in enumerate(chunk):
                    value |= o[1] << (8 + 4 * n)
                put_cell(w['s'] + chunk[0][0], value)
                packs += 1
                saved += len(chunk) - 1
                i += len(chunk)
        del run[:]

    for j, (k, pl) in enumerate(ops):
        if k == 'P':
            total += 1
        fits = k == 'P' and pl in ALPHA
        if fits:
            packable += 1
        if fits and (j == 0 or at[j] not in breaks):
            run.append((at[j], ALPHA[pl]))
        else:
            flush()
            if fits:
                run.append((at[j], ALPHA[pl]))
    flush()

open(OUT, 'wb').write(bytes(blob))
old = len(blob) - HDR
print("alphabet: %s" % " ".join(alpha))
print("packs %d in %d runs; %d of %d primitive cells are in the alphabet; "
      "%d cells folded away" % (packs, runs, packable, total, saved))
print("image %d bytes; %d bytes would be saved by a relocating build "
      "(%.3fx)" % (old, saved * CELL, (old - saved * CELL) / old))
